name = "Dark Shark"
port = 44445

center_of_mass = [0.0, -0.035, 0.0]
motor_amperage_budget = 25.0
jerk_limit = 40.0

# This is dummy data
[motor_config.X3d.seed_motor]
# position = [0.325, 0.355, 0.241]
# FIXME: This is wrong i think
position = [0.19, 0.21, 0.09]
orientation = [-0.254, 0.571, -0.781]
direction = "CounterClockwise"

[motor_config.X3d.motors]
FrontRightBottom = 0
BackRightBottom = 1
BackRightTop = 2
FrontLeftTop = 3
FrontLeftBottom = 4
BackLeftBottom = 5
BackLeftTop = 6
FrontRightTop = 7

[servo_config.servos]
FrontCameraRotate = { pwm_channel = 15, cameras = ["Front"] }
Claw1 = { pwm_channel = 14, cameras = ["Front"] }
Claw2 = { pwm_channel = 13, cameras = ["Front"] }
Claw3 = { pwm_channel = 12, cameras = ["Front"] }


[cameras."/dev/video2"]
name = "Front"
transform = { position = { x = 0.0, y = 1.0, z = 0.0 }, rotation = { yaw = 0.0, pitch = 0.0, roll = 0.0 } }

[cameras."/dev/video6"]
name = "Top"
transform = { position = { x = 0.0, y = 0.0, z = 1.0 }, rotation = { yaw = 0.0, pitch = -90.0, roll = 0.0 } }

[cameras."/dev/video10"]
name = "A"
transform = { position = { x = 0.0, y = 0.0, z = -1.0 }, rotation = { yaw = 0.0, pitch = 90.0, roll = 0.0 } }

[cameras."/dev/video14"]
name = "B"
transform = { position = { x = 0.0, y = -1.0, z = 0.0 }, rotation = { yaw = -180.0, pitch = 0.0, roll = 0.0 } }

[cameras."/dev/video18"]
name = "C"
transform = { position = { x = 1.0, y = 0.0, z = 0.0 }, rotation = { yaw = -90.0, pitch = 0.0, roll = 0.0 } }
