name = "Demo"
motor_amperage_budget = 20.0

# This is dummy data
[motor_config.X3d.seed_motor]
position = [
    0.325,
    0.355,
    0.241,
]
orientation = [
    0.254,
    -0.571,
    0.781,
]
direction = "Clockwise"

[motor_config.X3d.motors]
FrontRightTop = 0
FrontRightBottom = 6
FrontLeftTop = 3
FrontLeftBottom = 2
BackRightTop = 1
BackRightBottom = 7
BackLeftTop = 5
BackLeftBottom = 4

[cameras."/dev/video2"]
name = "Front"
transform = { position = { x = 0.0, y = 1.0, z = 0.0 }, rotation = { yaw = 0.0, pitch = 0.0, roll = 0.0 }}

[cameras."/dev/video6"]
name = "Top"
transform = { position = { x = 0.0, y = 0.0, z = 1.0 }, rotation = { yaw = 0.0, pitch = -90.0, roll = 0.0 }}
