[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
networking = { path = "../networking" }

serde = { version = "1", features = ["derive"] }
bincode = "1"

anyhow = "1"
thiserror = "1"
tracing = "0.1"

mint = { version = "0.5", features = ["serde"] }
rand = "0.8"
ahash = "0.8"

bevy_ecs = { path = "../../bevy-fork/crates/bevy_ecs/" }

[dev-dependencies]
tracing-subscriber = "0.3"
